In [18]:
# load the iris dataset as an example 
from sklearn.datasets import load_iris 
iris = load_iris() 
  
# store the feature matrix (X) and response vector (y) 
X = iris.data 
y = iris.target 
  
# store the feature and target names 
feature_names = iris.feature_names 
target_names = iris.target_names 
  
# printing features and target names of our dataset 
print("Feature names:", feature_names) 
print("Target names:", target_names) 
  
# X and y are numpy arrays 
print("\nType of X is:", type(X)) 
  
# printing first 5 input rows 
print("\nFirst 5 rows of X:\n", X[:5])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

Type of X is: <class 'numpy.ndarray'>

First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [19]:
# iris.target
# iris.data
# iris.feature_names
# iris.target_names

In [20]:
import pandas as pd
  
# reading csv file 
data = pd.read_csv('weather.csv') 
  
# shape of dataset 
print("Shape:", data.shape) 
  
# column names 
print("\nFeatures:", data.columns) 
  
# storing the feature matrix (X) and response vector (y) 
X = data[data.columns[:-1]] 
y = data[data.columns[-1]] 
  
# printing first 5 rows of feature matrix 
print("\nFeature matrix:\n", X.head()) 
  
# printing first 5 values of response vector 
print("\nResponse vector:\n", y.head())

FileNotFoundError: [Errno 2] No such file or directory: 'weather.csv'